# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: digit_delim 0.3.1 ruby lib

Gem::Specification.new do |s|
  s.name = "digit_delim".freeze
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["YAMAMOTO, Masayuki".freeze]
  s.date = "2021-07-13"
  s.description = "methods of num-string formatter, converter which extends String class".freeze
  s.email = "martin.route66.blues+github@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "ReadMe.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "Rakefile",
    "ReadMe.md",
    "VERSION",
    "digit_delim.gemspec",
    "lib/digit_delim.rb",
    "lib/kannum.rb",
    "test/helper.rb",
    "test/test_digit_delim.rb",
    "test/test_kannum.rb"
  ]
  s.homepage = "http://github.com/mephistobooks/digit_delim".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.2.20".freeze
  s.summary = "A little num-string formatter, converter.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<bundler>.freeze, [">= 1.3.5"])
    s.add_development_dependency(%q<jeweler>.freeze, [">= 1.8.4"])
    s.add_development_dependency(%q<test-unit>.freeze, [">= 3.1.5"])
  else
    s.add_dependency(%q<bundler>.freeze, [">= 1.3.5"])
    s.add_dependency(%q<jeweler>.freeze, [">= 1.8.4"])
    s.add_dependency(%q<test-unit>.freeze, [">= 3.1.5"])
  end
end

