# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: digit_delim 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "digit_delim"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["YAMAMOTO, Masayuki"]
  s.date = "2016-07-30"
  s.description = "methods of num-string formatter, converter which extends String class"
  s.email = "martin.route66.blues+github@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Rakefile",
    "ReadMe.md",
    "VERSION",
    "digit_delim.gemspec",
    "lib/digit_delim.rb",
    "lib/kannum.rb",
    "test/helper.rb",
    "test/test_digit_delim.rb",
    "test/test_kannum.rb"
  ]
  s.homepage = "http://github.com/mephistobooks/digit_delim"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "A little num-string formatter, converter."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_development_dependency(%q<test-unit>, [">= 3.1.5"])
    else
      s.add_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_dependency(%q<test-unit>, [">= 3.1.5"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 1.3.5"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    s.add_dependency(%q<test-unit>, [">= 3.1.5"])
  end
end

